"""
Checkpoint writer — markdown reports for dispatch monitoring.

After every batch, a checkpoint markdown file is written to
audit/orchestrator/checkpoints/. These are formatted for readability on an
iPad and give a concise "what happened, what's next" view.
"""

from __future__ import annotations

import json
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

REPO_ROOT = Path(__file__).resolve().parents[2]
CHECKPOINT_DIR = REPO_ROOT / "audit" / "orchestrator" / "checkpoints"
LATEST_LINK = REPO_ROOT / "audit" / "orchestrator" / "LATEST.md"


def _timestamp() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%d_%H%M%SZ")


def write_checkpoint(
    state: dict[str, Any],
    phase_info: dict[str, Any],
    batch_result: dict[str, Any],
    validation_report: dict[str, Any],
    next_batch: list[str],
    notes: str = "",
) -> Path:
    CHECKPOINT_DIR.mkdir(parents=True, exist_ok=True)
    ts = _timestamp()
    phase = state["phase_index"]
    batch = state["batch_index"]
    path = CHECKPOINT_DIR / f"{ts}_phase{phase:02d}_batch{batch:04d}.md"

    done = state["totals"]["entities_done"]
    total = state["totals"]["entities_total"]
    pct = (done / total * 100) if total else 0.0

    lines: list[str] = []
    lines.append(f"# Checkpoint — {ts}")
    lines.append("")
    lines.append(f"**Phase:** {phase} — {state['phase_name']}")
    lines.append(f"**Batch:** {batch}")
    lines.append(f"**Overall progress:** {done}/{total} ({pct:.1f}%)")
    lines.append(f"**Last commit:** `{state.get('last_commit_sha') or '—'}`")
    lines.append("")
    lines.append("## Batch outcome")
    lines.append("")
    if batch_result.get("written"):
        lines.append(f"- Written: {len(batch_result['written'])} entities")
        for eid in batch_result["written"]:
            lines.append(f"  - `{eid}`")
    if batch_result.get("not_found"):
        lines.append(f"- Not found: {batch_result['not_found']}")
    if batch_result.get("changed") is not None:
        lines.append(f"- Normalized: {batch_result['changed']} entities")

    lines.append("")
    lines.append("## Validation")
    lines.append("")
    status = "PASS" if validation_report.get("pass") else "FAIL"
    lines.append(f"- Status: **{status}**")
    lines.append(f"- Total errors: {validation_report.get('total_errors', 0)}")
    if not validation_report.get("pass"):
        lines.append("")
        lines.append("### Errors")
        for eid, checks in validation_report.get("checks", {}).items():
            for check, errs in checks.items():
                if errs:
                    lines.append(f"- **{eid} / {check}**")
                    for e in errs[:5]:
                        lines.append(f"  - {e}")
                    if len(errs) > 5:
                        lines.append(f"  - … and {len(errs) - 5} more")

    lines.append("")
    lines.append("## Phase progress")
    lines.append("")
    lines.append(f"- Phase name: {phase_info.get('name')}")
    lines.append(f"- Phase entity count: {phase_info.get('count')}")
    phase_done = phase_info.get("done", 0)
    phase_total = phase_info.get("count", 0)
    phase_pct = (phase_done / phase_total * 100) if phase_total else 0.0
    lines.append(f"- Phase progress: {phase_done}/{phase_total} ({phase_pct:.1f}%)")

    lines.append("")
    lines.append("## Next batch")
    lines.append("")
    if next_batch:
        lines.append(f"Ready to process {len(next_batch)} entities:")
        for eid in next_batch:
            lines.append(f"- `{eid}`")
    else:
        lines.append("_No pending entities in current phase. Ready to advance._")

    if notes:
        lines.append("")
        lines.append("## Notes")
        lines.append("")
        lines.append(notes)

    lines.append("")
    lines.append("---")
    lines.append(
        "_Generated by `tools/orchestrator` — resume with `python -m "
        "tools.orchestrator.cli status`._"
    )

    path.write_text("\n".join(lines))

    # Update LATEST.md pointer
    LATEST_LINK.write_text("\n".join(lines))

    return path


def write_session_resume_card(state: dict[str, Any]) -> Path:
    """A tiny one-screen markdown pointing at where we are, for dispatch."""
    path = REPO_ROOT / "audit" / "orchestrator" / "RESUME.md"
    done = state["totals"]["entities_done"]
    total = state["totals"]["entities_total"]
    pct = (done / total * 100) if total else 0.0
    lines = [
        "# Orchestrator Resume Card",
        "",
        f"**Updated:** {state['updated_at']}",
        f"**Phase:** {state['phase_index']} — {state['phase_name']}",
        f"**Batch:** {state['batch_index']}",
        f"**Progress:** {done}/{total} ({pct:.1f}%)",
        f"**Last commit:** `{state.get('last_commit_sha') or '—'}`",
        f"**Last checkpoint:** {state.get('last_checkpoint') or '—'}",
        "",
        "## Resume command",
        "",
        "```bash",
        "python -m tools.orchestrator.cli status",
        "python -m tools.orchestrator.cli next",
        "```",
    ]
    path.write_text("\n".join(lines))
    return path
